export {default as Navbar} from "./Navbar"
export {default as Exchanges} from "./Exchanges"
export {default as HomePage} from "./Homepage"
export {default as News} from "./News"
export {default as Cryptocurrencies} from "./CryptoCurrencies"
export {default as CryptoDetails} from "./CryptoDetails"